---
- name: "Update apt packages"
  become: true
  shell:
    curl -sL https://deb.nodesource.com/setup_13.x -o /tmp/nodesource_setup.sh

- name: "Install npm and nodejs 16"
  become: true
  apt:
    name: ["npm", "nodejs"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present